# config.yaml
commit: true         # Abilita commit automatico se non in ambiente Netlify
max_files_per_folder: 50  # Numero massimo di file prima che la cartella venga raggruppata
git:
  user_email: "auto@local.com"
  user_name: "Auto Commit"
tree_command: "tree -a"  # Comando per generare l'albero dei file