name: Build and Deploy GitHub Pages (Publishing on main)

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  id-token: write

concurrency:
  group: pages_build_deployment
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout del repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Setup Node (se il progetto usa Node.js per la build; altrimenti, rimuovi questo step)
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # 3) Installa le dipendenze ed esegui la build
      - name: Install dependencies & Build
        run: |
          echo "Installing dependencies..."
          npm install
          echo "Running build..."
          npm run build
          # Assicurati che questo comando generi la cartella "build".
          
      # 4) Debug: List dei file nella cartella di output
      - name: List build folder
        run: ls -la build || echo "Build folder not found."

      # 5) Carica l’artifact (usiamo actions/upload-artifact@v4)
      - name: Upload artifact for Pages
        uses: actions/upload-artifact@v4
        with:
          name: iframeAirdropArtifact
          path: build   # Modifica questo percorso se la cartella di output è diversa

      # 6) Deploy su GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          artifact_name: iframeAirdropArtifact
