name: Deploy GitHub Pages (Static)

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  id-token: write

concurrency:
  group: pages_build_deployment
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout del repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Debug: Elenca i file nella root
      - name: List repository files
        run: ls -la

      # 3) Debug: Elenca i file nella cartella "public"
      - name: List "public" folder contents
        run: ls -la public || echo "Folder 'public' not found"

      # 4) Upload dell'artifact
      - name: Upload artifact for Pages
        uses: actions/upload-artifact@v4
        with:
          name: mySiteArtifact
          path: public  # Assicurati che questa cartella contenga i file statici da pubblicare

      # 5) Deploy su GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          artifact_name: mySiteArtifact
