name: Deploy GitHub Pages (Static)

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  id-token: write

# Evita che un nuovo push annulli i run in corso
concurrency:
  group: pages_build_deployment
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout del repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Debug: List dei file nella root del repository
      - name: List repository files
        run: ls -la

      # 3) Debug: List dei file nella cartella "public"
      - name: List "public" folder contents
        run: ls -la public || echo "Folder 'public' not found"

      # 4) Carica l'artifact (il sito statico) utilizzando actions/upload-artifact@v4
      - name: Upload artifact for Pages
        uses: actions/upload-artifact@v4
        with:
          name: mySiteArtifact      # Questo nome viene usato anche nello step successivo
          path: public              # Specifica il percorso della cartella contenente i file statici

      # 5) Deploy su GitHub Pages usando actions/deploy-pages@v2
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}  # Assicurati di avere il secret MY_GITHUB_TOKEN impostato nel repository
          artifact_name: mySiteArtifact
