name: Deploy GitHub Pages (Static)

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  id-token: write

concurrency:
  group: pages_build_deployment
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Assemble public folder
        run: bash scripts/assemble_public.sh

      - name: List "public" folder contents
        run: |
          if [ -d public ]; then
            echo "Files in public folder:"
            ls -la public
          else
            echo "Folder 'public' not found!"
            exit 1
          fi

      - name: Upload artifact for Pages
        uses: actions/upload-artifact@v4
        with:
          name: mySiteArtifact
          path: public

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          artifact_name: mySiteArtifact
