name: Build and Deploy GitHub Pages

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  id-token: write

concurrency:
  group: pages_build_deployment
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies & Build
        run: |
          npm install
          npm run build
          # produce i file in ./build

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: mySiteArtifact         # Nome artefatto
          path: ./build               # Cartella generata

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}  # O secrets.GITHUB_TOKEN
          artifact_name: mySiteArtifact          # Lo stesso nome definito sopra
