name: Build and Deploy GitHub Pages

on:
  push:
    branches: [ "main" ]  # Cambia se vuoi un altro branch per il deploy

permissions:
  contents: write
  id-token: write

# Se vuoi che un nuovo push NON annulli i run precedenti, setta concurrency:
concurrency:
  group: pages_build_deployment
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Effettua il checkout del repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Build del tuo sito (esempio con npm)
      - name: Install dependencies & Build
        run: |
          echo "Installing dependencies..."
          npm install
          echo "Running build..."
          npm run build
          # Supponendo che la cartella di output sia ./build;
          # se invece si chiama ./dist o ./public, cambiala sotto.

      # 3) Carica l'artifact per Pages (v2 per evitare la deprecazione di v3)
      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./build  # la cartella generata dalla build
          # artifact_name: mySiteArtifact  # (opzionale) se vuoi nominare l'artifact

      # 4) Pubblica su GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          # Se vuoi usare un token personalizzato: 
          # token: ${{ secrets.MY_GITHUB_TOKEN }}
          # Altrimenti usa GITHUB_TOKEN integrato:
          token: ${{ secrets.GITHUB_TOKEN }}
          #
          # Se sopra hai nominato l'artifact:
          # artifact_name: mySiteArtifact
          #
          # Se vuoi un branch diverso da 'gh-pages':
          # branch: gh-pages
