name: Deploy GitHub Pages (Root Deployment)

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  id-token: write

concurrency:
  group: pages_build_deployment
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List repository files (debug)
        run: ls -la

      # Se i file statici sono nella root, usa il percorso "."
      - name: Upload artifact for Pages
        uses: actions/upload-artifact@v4
        with:
          name: mySiteArtifact
          path: .  # Usa la root; assicurati che contenga solo i file da pubblicare

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          artifact_name: mySiteArtifact
