name: Build and Deploy GitHub Pages (Publishing on main)

on:
  push:
    branches: [ "main" ]   # Build e deploy quando fai push su main

permissions:
  contents: write
  id-token: write

concurrency:
  group: pages_build_deployment
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      # 1) Checkout del repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Setup Node (se il tuo progetto usa Node.js)
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16  # Sostituisci con la versione che preferisci

      # 3) Installa dipendenze & build
      - name: Install dependencies & Build
        run: |
          npm install
          npm run build
          # Se la cartella di output è ./build,
          # altrimenti modifica i riferimenti qui sotto.

      # 4) Carica manualmente i file come artifact (usa upload-artifact@v2)
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: mySiteArtifact            # Nome dell'artifact
          path: ./build                  # Cartella con i file HTML/CSS/JS generati

      # 5) Deploy su GitHub Pages (restando su main)
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          # Se vuoi un token personalizzato, sostituisci con MY_GITHUB_TOKEN
          token: ${{ secrets.MY_GITHUB_TOKEN }}

          artifact_name: mySiteArtifact   # Deve corrispondere al "name:" sopra
          branch: main                   # Pubblica su main (impostato in Settings → Pages)
