name: Build and Deploy GitHub Pages

on:
  push:
    branches: [ "main" ]   # o il branch che preferisci

# Permessi: abilitano id-token e scrittura su contenuti
permissions:
  contents: write
  id-token: write

# (Opzionale) se non vuoi concurrency che cancella i run
# concurrency:
#   group: pages_build_deployment
#   cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      # Esempio di build
      - name: Build site
        run: |
          echo "Here you'd do npm install && npm run build or similar"

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # Se servono parametri, puoi aggiungerli (branch: gh-pages, etc.)
