name: Build and Deploy GitHub Pages (Publishing on main)

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  id-token: write

# Evita che un nuovo push annulli i run in corso:
concurrency:
  group: pages_build_deployment
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      # 1) Checkout del repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Setup Node (se il tuo progetto usa Node.js; altrimenti rimuovi questo step)
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # 3) Installa le dipendenze ed esegui la build
      - name: Install dependencies & Build
        run: |
          echo "Installing dependencies..."
          npm install
          echo "Running build..."
          npm run build
          # Assicurati che il comando generi i file nella cartella ./build
          # Se il tuo output è in una cartella diversa (es. ./dist o ./public), sostituisci di conseguenza.

      # 4) Carica l'artifact (utilizza actions/upload-artifact@v3, non deprecato)
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: mySiteArtifact      # Nome dell'artifact (deve essere usato anche nello step successivo)
          path: ./build            # Cartella contenente i file generati dalla build

      # 5) Deploy su GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}  # Assicurati che questo secret sia impostato nel repository
          artifact_name: mySiteArtifact          # Deve corrispondere al nome usato nello step di upload
          branch: main                          # Pubblica su main (se le Settings di Pages sono configurate su questo branch)
