name: Build and Deploy GitHub Pages

on:
  push:
    branches: [ "main" ]  # o il branch che preferisci

permissions:
  contents: write

concurrency:
  group: pages_build_deployment
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      # ... i tuoi step per buildare e pubblicare su GH Pages ...
      # Ad esempio, se hai un workflow React / Jekyll / etc.

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          branch: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}
